<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MinimalWorkspaceTimeline</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Novolis.Workspaces.FileSystem\Novolis.Workspaces.FileSystem.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Workspaces.Snapshots\Novolis.Workspaces.Snapshots.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Workspaces.Timeline\Novolis.Workspaces.Timeline.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Timeline.FileSystem\Novolis.Timeline.FileSystem.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Timeline.Presentation\Novolis.Timeline.Presentation.csproj" />
  </ItemGroup>
</Project>
