<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="TUnit" Version="1.44.39" />
    <PackageVersion Include="System.IO.Abstractions" Version="22.1.0" />
    <PackageVersion Include="System.IO.Abstractions.TestingHelpers" Version="22.1.0" />
  </ItemGroup>
</Project>
