using System.Text;
using System.Text.RegularExpressions;

namespace Novolis.Workspaces.DotNet.Slnx;

/// <summary>Writes Novolis.PackageToProject.props from packable projects in the forest.</summary>
public static class PackageToProjectMapWriter
{
    private static readonly Regex ExcludeRepo = new(
        @"workflows|governance|lab|utilities|apps|installer|experimental|smoketest|template-dotnet",
        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    public static int Write(string workspaceRoot, string outputPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(workspaceRoot);
        workspaceRoot = Path.GetFullPath(workspaceRoot);
        var entries = new List<(string PackageId, string RelPath)>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var repo in Directory.GetDirectories(workspaceRoot, "novolis-*"))
        {
            var repoName = Path.GetFileName(repo);
            if (ExcludeRepo.IsMatch(repoName))
                continue;

            foreach (var csproj in Directory.EnumerateFiles(repo, "*.csproj", SearchOption.AllDirectories))
            {
                if (csproj.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase)
                    || csproj.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase))
                    continue;

                var text = File.ReadAllText(csproj);
                if (!Regex.IsMatch(text, @"<IsPackable>\s*true\s*</IsPackable>", RegexOptions.IgnoreCase))
                    continue;

                var idMatch = Regex.Match(text, @"<PackageId>\s*([^<]+?)\s*</PackageId>");
                var packageId = idMatch.Success ? idMatch.Groups[1].Value.Trim() : Path.GetFileNameWithoutExtension(csproj);
                if (!seen.Add(packageId))
                    throw new InvalidOperationException($"Duplicate PackageId '{packageId}' (also in {repoName}). Fix before regenerating map.");

                var rel = Path.GetRelativePath(workspaceRoot, csproj).Replace('/', '\\');
                entries.Add((packageId, rel));
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("<!--");
        sb.AppendLine("  AUTO-GENERATED by Novolis.Workspaces.DotNet.Slnx — do not edit.");
        sb.AppendLine("  Regenerate: novolis-solution generate");
        sb.AppendLine("-->");
        sb.AppendLine("<Project>");
        sb.AppendLine("  <ItemGroup>");
        foreach (var entry in entries.OrderBy(e => e.PackageId, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine($"    <NovolisPackageProject Include=\"{entry.PackageId}\">");
            sb.AppendLine($"      <ProjectPath>$(NovolisLibraryRoot)\\{entry.RelPath}</ProjectPath>");
            sb.AppendLine("    </NovolisPackageProject>");
        }

        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine("</Project>");
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString().TrimEnd() + Environment.NewLine, new UTF8Encoding(false));
        return entries.Count;
    }
}
