using System.Text;
using Novolis.Workspaces.DotNet.Roslyn;
using Novolis.Workspaces.DotNet.Slnx;

namespace Novolis.Workspaces.DotNet.Indexing;

/// <summary>Options for generating a typed C# exploration façade from a catalog.</summary>
public sealed record SolutionExplorationGenerationOptions(bool PublicTypesOnly = true);

/// <summary>Generated C# that exposes named projects, namespaces, and types as real members.</summary>
public sealed record GeneratedSolutionExploration(
    string Source,
    string Namespace,
    string SolutionTypeName,
    string WalkTypeName);

/// <summary>
/// Emits a C# façade whose property chain is the typed exploration path, for example
/// <c>solution.Projects.DemoLib.Services.IdentityService</c>.
/// </summary>
public static class SolutionExplorationGenerator
{
    public const string DefaultNamespace = "Novolis.Workspaces.DotNet.Generated";
    public const string SolutionTypeName = "GeneratedSolution";
    public const string WalkTypeName = "GeneratedExploration";

    private static readonly HashSet<string> Keywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
        "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
        "virtual", "void", "volatile", "while", "record", "required", "file", "scoped",
    };

    public static GeneratedSolutionExploration Generate(
        SolutionCatalog catalog,
        SolutionExplorationGenerationOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(catalog);
        options ??= new SolutionExplorationGenerationOptions();

        var projects = catalog.Projects
            .Select((project, index) => ProjectModel.Create(project, index, options.PublicTypesOnly))
            .ToArray();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.Linq;");
        source.AppendLine("using System.Text;");
        source.AppendLine("using Novolis.Workspaces.DotNet.Indexing;");
        source.AppendLine("using Novolis.Workspaces.DotNet.Roslyn;");
        source.AppendLine();
        source.AppendLine($"namespace {DefaultNamespace};");
        source.AppendLine();
        source.AppendLine($"public sealed class {SolutionTypeName}");
        source.AppendLine("{");
        source.AppendLine($"    public {SolutionTypeName}(SolutionCatalog catalog)");
        source.AppendLine("    {");
        source.AppendLine("        ArgumentNullException.ThrowIfNull(catalog);");
        source.AppendLine("        Catalog = catalog;");
        source.AppendLine("        Projects = new GeneratedProjects(catalog);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public SolutionCatalog Catalog { get; }");
        source.AppendLine("    public GeneratedProjects Projects { get; }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public sealed class GeneratedProjects");
        source.AppendLine("{");
        source.AppendLine("    public GeneratedProjects(SolutionCatalog catalog)");
        source.AppendLine("    {");
        source.AppendLine("        ArgumentNullException.ThrowIfNull(catalog);");
        foreach (var project in projects)
        {
            source.AppendLine(
                $"        {project.PropertyName} = new {project.TypeName}(Find(catalog, {CSharpString(project.RelativePath)}));");
        }

        source.AppendLine("    }");
        source.AppendLine();
        foreach (var project in projects)
            source.AppendLine($"    public {project.TypeName} {project.PropertyName} {{ get; }}");

        source.AppendLine();
        source.AppendLine("    private static SolutionCatalogProject Find(SolutionCatalog catalog, string relativePath) =>");
        source.AppendLine("        catalog.Projects.First(project =>");
        source.AppendLine("            string.Equals(project.Project.RelativePath, relativePath, StringComparison.OrdinalIgnoreCase));");
        source.AppendLine("}");

        foreach (var project in projects)
            WriteProjectTypes(source, project);

        source.AppendLine();
        source.AppendLine($"public static class {WalkTypeName}");
        source.AppendLine("{");
        source.AppendLine("    public static string Walk(SolutionCatalog catalog)");
        source.AppendLine("    {");
        source.AppendLine($"        var solution = new {SolutionTypeName}(catalog);");
        source.AppendLine("        var builder = new StringBuilder();");
        foreach (var project in projects)
        {
            source.AppendLine(
                $"        builder.AppendLine(\"solution.Projects.{project.PropertyName}.RelativePath => \" + solution.Projects.{project.PropertyName}.RelativePath);");
            WriteWalk(source, $"solution.Projects.{project.PropertyName}", project.Root);
        }

        source.AppendLine("        return builder.ToString();");
        source.AppendLine("    }");
        source.AppendLine("}");

        return new GeneratedSolutionExploration(
            source.ToString(),
            DefaultNamespace,
            SolutionTypeName,
            $"{DefaultNamespace}.{WalkTypeName}");
    }

    private static void WriteProjectTypes(StringBuilder source, ProjectModel project)
    {
        source.AppendLine();
        source.AppendLine($"public sealed class {project.TypeName}");
        source.AppendLine("{");
        source.AppendLine($"    public {project.TypeName}(SolutionCatalogProject project)");
        source.AppendLine("    {");
        source.AppendLine("        ArgumentNullException.ThrowIfNull(project);");
        source.AppendLine("        Project = project;");
        foreach (var child in project.Root.Children)
            source.AppendLine($"        {child.PropertyName} = new {child.TypeName}(project);");

        WriteTypeAssignments(source, project.Root.Types);
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public SolutionCatalogProject Project { get; }");
        source.AppendLine("    public string RelativePath => Project.Project.RelativePath;");
        foreach (var child in project.Root.Children)
            source.AppendLine($"    public {child.TypeName} {child.PropertyName} {{ get; }}");

        WriteTypeProperties(source, project.Root.Types);
        source.AppendLine("}");

        WriteNamespaceTypes(source, project.Root.Children);
    }

    private static void WriteNamespaceTypes(StringBuilder source, IEnumerable<NamespaceModel> nodes)
    {
        foreach (var node in nodes)
        {
            source.AppendLine();
            source.AppendLine($"public sealed class {node.TypeName}");
            source.AppendLine("{");
            source.AppendLine($"    public {node.TypeName}(SolutionCatalogProject project)");
            source.AppendLine("    {");
            source.AppendLine("        ArgumentNullException.ThrowIfNull(project);");
            foreach (var child in node.Children)
                source.AppendLine($"        {child.PropertyName} = new {child.TypeName}(project);");

            WriteTypeAssignments(source, node.Types);
            source.AppendLine("    }");
            source.AppendLine();
            foreach (var child in node.Children)
                source.AppendLine($"    public {child.TypeName} {child.PropertyName} {{ get; }}");

            WriteTypeProperties(source, node.Types);
            source.AppendLine("}");
            WriteNamespaceTypes(source, node.Children);
        }
    }

    private static void WriteTypeAssignments(StringBuilder source, IReadOnlyList<TypeModel> types)
    {
        foreach (var type in types)
        {
            source.AppendLine(
                $"        {type.PropertyName} = project.Semantic.Types.First(candidate => string.Equals(candidate.MetadataName, {CSharpString(type.MetadataName)}, StringComparison.Ordinal));");
        }
    }

    private static void WriteTypeProperties(StringBuilder source, IReadOnlyList<TypeModel> types)
    {
        foreach (var type in types)
            source.AppendLine($"    public SemanticType {type.PropertyName} {{ get; }}");
    }

    private static void WriteWalk(
        StringBuilder source,
        string prefix,
        NamespaceModel node)
    {
        foreach (var type in node.Types)
        {
            source.AppendLine(
                $"        builder.AppendLine(\"{prefix}.{type.PropertyName} => \" + {prefix}.{type.PropertyName}.MetadataName);");
        }

        foreach (var child in node.Children)
            WriteWalk(source, $"{prefix}.{child.PropertyName}", child);
    }

    private static string CSharpString(string value)
    {
        return "\""
            + value
                .Replace("\\", "\\\\", StringComparison.Ordinal)
                .Replace("\"", "\\\"", StringComparison.Ordinal)
                .Replace("\r", "\\r", StringComparison.Ordinal)
                .Replace("\n", "\\n", StringComparison.Ordinal)
            + "\"";
    }

    private static string ToIdentifier(string name, HashSet<string> used)
    {
        var builder = new StringBuilder();
        foreach (var character in name)
        {
            if (char.IsLetterOrDigit(character) || character is '_')
                builder.Append(character);
            else if (builder.Length > 0 && builder[^1] is not '_')
                builder.Append('_');
        }

        if (builder.Length == 0 || !char.IsLetter(builder[0]) && builder[0] is not '_')
            builder.Insert(0, '_');

        var identifier = builder.ToString();
        if (Keywords.Contains(identifier))
            identifier = "@" + identifier;

        var unique = identifier;
        var suffix = 2;
        while (!used.Add(unique))
        {
            unique = identifier + "_" + suffix;
            suffix++;
        }

        return unique;
    }

    private static string ToTypeNamePart(string name)
    {
        var identifier = ToIdentifier(name, []);
        identifier = identifier.TrimStart('@');
        return Keywords.Contains(identifier) ? "_" + identifier : identifier;
    }

    private sealed class ProjectModel
    {
        private ProjectModel(
            string relativePath,
            string propertyName,
            string typeName,
            NamespaceModel root)
        {
            RelativePath = relativePath;
            PropertyName = propertyName;
            TypeName = typeName;
            Root = root;
        }

        public string RelativePath { get; }
        public string PropertyName { get; }
        public string TypeName { get; }
        public NamespaceModel Root { get; }

        public static ProjectModel Create(SolutionCatalogProject project, int index, bool publicTypesOnly)
        {
            var usedProperties = new HashSet<string>(StringComparer.Ordinal) { "Project", "RelativePath" };
            var stem = Path.GetFileNameWithoutExtension(project.Project.RelativePath);
            if (string.IsNullOrWhiteSpace(stem))
                stem = "Project" + index;

            var propertyName = ToIdentifier(stem, usedProperties);
            var typeName = propertyName.TrimStart('@') + "Project";
            var root = new NamespaceModel("root", "Root", "UnusedRoot", ["Project", "RelativePath"]);
            foreach (var type in project.Semantic.Types)
            {
                if (publicTypesOnly && !type.IsPublic)
                    continue;

                AddType(root, type, typeName);
            }

            return new ProjectModel(project.Project.RelativePath, propertyName, typeName, root);
        }

        private static void AddType(NamespaceModel root, SemanticType type, string projectTypeName)
        {
            var segments = string.IsNullOrWhiteSpace(type.Namespace)
                ? []
                : type.Namespace.Split('.', StringSplitOptions.RemoveEmptyEntries);
            var node = root;
            var path = projectTypeName;
            foreach (var segment in segments)
            {
                path += "_" + ToTypeNamePart(segment);
                var child = node.Children.FirstOrDefault(candidate =>
                    string.Equals(candidate.Segment, segment, StringComparison.Ordinal));
                if (child is null)
                {
                    var used = node.UsedPropertyNames;
                    var propertyName = ToIdentifier(segment, used);
                    child = new NamespaceModel(segment, propertyName, path + "Namespace", used);
                    node.Children.Add(child);
                }

                node = child;
            }

            var typeName = SimpleTypeName(type);
            node.Types.Add(new TypeModel(type.MetadataName, ToIdentifier(typeName, node.UsedPropertyNames)));
        }

        private static string SimpleTypeName(SemanticType type)
        {
            var metadata = type.MetadataName;
            var plus = metadata.LastIndexOf('+');
            if (plus >= 0 && plus < metadata.Length - 1)
                return metadata[(plus + 1)..];

            if (!string.IsNullOrWhiteSpace(type.Namespace)
                && metadata.StartsWith(type.Namespace + ".", StringComparison.Ordinal))
            {
                return metadata[(type.Namespace.Length + 1)..];
            }

            var dot = metadata.LastIndexOf('.');
            return dot >= 0 && dot < metadata.Length - 1 ? metadata[(dot + 1)..] : metadata;
        }
    }

    private sealed class NamespaceModel
    {
        public NamespaceModel(string segment, string propertyName, string typeName, HashSet<string> inheritedUsed)
        {
            Segment = segment;
            PropertyName = propertyName;
            TypeName = typeName;
            UsedPropertyNames = new HashSet<string>(inheritedUsed, StringComparer.Ordinal);
        }

        public string Segment { get; }
        public string PropertyName { get; }
        public string TypeName { get; }
        public HashSet<string> UsedPropertyNames { get; }
        public List<NamespaceModel> Children { get; } = [];
        public List<TypeModel> Types { get; } = [];
    }

    private sealed record TypeModel(string MetadataName, string PropertyName);
}
